#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/Pictures/wallpapers/wallhaven-5gz7k7.jpg &
xrandr --rate 144 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		12

bspc config top_padding    0
bspc config bottom_padding 0

bspc config focused_border_color   "#92a65e"
bspc config normal_border_color    "#99968b"

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1' follow=on focus=on state=tiled
bspc rule -a Emacs desktop='^2' follow=on focus=on state=tiled

$HOME/.config/polybar/launch.sh
