#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/Pictures/wallpapers/wallhaven-jxmwvm.png &
xrandr --rate 144 &
emacs --daemon &

bspc monitor -d 1 2 3 4 5

bspc config border_width	0
bspc config window_gap		12

bspc config top_padding 36
bspc config bottom_padding 0

bspc config focused_border_color   "#ffffff"
bspc config normal_border_color    "#000000"

bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs desktop='^2' follow=on focus=on state=tiled

$HOME/.config/polybar/launch.sh 
