#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale --randomize ~/Pictures/wallpapers/navy/6.png &
xrandr --rate 144 &

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch.sh

bspc config border_width	2
bspc config window_gap		16

bspc config top_padding    0  # Adjust to match Polybar's height
bspc config bottom_padding 0

bspc config focused_border_color   "#cfaf01"   # Red for focused window
bspc config normal_border_color    "#343b4d"   # Gray for unfocused windows

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs desktop='^1'
bspc rule -a Chromium desktop='^1'
