[general]
import = [
    "~/.config/alacritty/themes/wombat.toml"
]

[window]
padding = { x = 3, y = 3 }

[font]
normal = { family = "Monospace", style = "regular" }
bold = { family = "Monospace", style = "regular" }
size = 11
